### PR TITLE
Repo Refresh

### PR DESCRIPTION
**Pull request by GrantBirki**
# Repo Refresh

This pull request does the following:

- Upgrades to the latest stable version of Ruby
- Upgrades to the latest version of `entitlements-app`

### CODE REVIEW

**Review by hortoncd — APPROVED** [review]

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Pull request merged**
